const mongoose = require('mongoose');
const AutoIncrement = require('mongoose-sequence')(mongoose);

const userDetailsSchema = new mongoose.Schema({
  sequenceNo: {
    type: Number,
    unique: true
  },
  user_id: { type: String, required: true},
  first_name: { type: String, required: true },
  middle_name: { type: String },
  last_name: { type: String },
  full_name: { type: String , required: true},
  email: { type: String , required: true},
  alt_email: { type: String },
  contact_no_1: { type: String, required: true },
  contact_no_2: { type: String },
  father_name: { type: String , required: true},
  father_contact_no: { type: String , required: true},
  father_dob: { type: Date, required: true },
  father_email: { type: String },
  mother_name: { type: String, required: true },
  mother_contact_no: { type: String , required: true},
  mother_dob: { type: Date , required: true},
  mother_email: { type: String },
  guardian_name: { type: String },
  guardian_contact_no: { type: String },
  guardian_dob: { type: Date },
  guardian_email: { type: String },
  guardian_relation: { type: String },
  current_address: { type: String , required: true},
  current_city: { type: String, required: true },
  current_state: { type: String , required: true},
  current_country: { type: String, required: true },
  current_pincode: { type: String, required: true },
  permanent_address: { type: String , required: true},
  permanent_city: { type: String, required: true },
  permanent_state: { type: String, required: true },
  permanent_pincode: { type: String, required: true },
  permanent_country: { type: String , required: true},
  gender: { type: String , required: true},
  dob: { type: Date , required: true},
  spouse_name: { type: String },
  spouse_dob: { type: Date },
  marital_status: { type: String },
  no_of_children: { type: Number },
  blood_group: { type: String , required: true},
  date_of_joining: { type: Date },
  date_of_resignation: { type: Date },
  leaving_date: { type: Date },
  employee_type: { type: String },
  employee_code: { type: String },
  tax_region: { type: String },
  bank_name: { type: String },
  bank_acc_no: { type: String },
  ifsc_code: { type: String },
  branch_address: { type: String },
  UAN_no: { type: String },
  PF_no: { type: String },
  esic_no: { type: String },
  category: { type: String , required: true},
  religion: { type: String, required: true },
  department_id: { type: String },
  designation_id: { type: String },
  standard: { type: String },
  section: { type: String },
  school_roll_no: { type: String },
  admission_no: { type: String },
  admission_date: { type: Date },
  profile_photo_path: { type: String },
  house_id: { type: String },
  created_by: { type: String },
  updated_by: { type: String },
  deactivated: { type: Boolean, default: false },
  deleted_on: { type: Date },
  status: { type: String , required: true}
}, { timestamps: true });

userDetailsSchema.plugin(AutoIncrement, {
  inc_field: 'sequenceNo',
  id: 'userDetails_seq'
});
module.exports = mongoose.model('UserDetails', userDetailsSchema);
